### ISSUE TITLE
process.cwd() + package.json should be dynamic

### ISSUE THREAD

**Issue by chengcyber** [vercel/webpack-asset-relocator-loader#112]
## Context

```
path.resolve(process.cwd(), 'package.json');
```

if `<project_dir>/package.json` exists, then the code emits `path.resolve(t.ab + 'package.json')` which t is treated as static. but in most case (I guess), it means to resolve the runtime project's package.json

Related: https://github.com/vercel/ncc/issues/444

The issue could be any filename accidentally exists in the project ncc build. but the `package.json` is the most outstanding one.

**Comment by guybedford** [comment]
Is this because the contents of the cwd of the build are not the same as the contents of the cwd of the runtime? If so, perhaps set the `cwd` option to point to the correct folder? The package.json should be emitted strictly speaking as that's what the asset emitter does.

We could possibly have a `cwd: false` option to disable cwd-based emissions.

**Comment by chengcyber** [comment]
Thanks you for the information about `cwd: false`. That is exactly what i want.

IMHO, `process.cwd()` should be not treated as static. i.e. `cwd: false` as default.

**Comment by guybedford** [comment]
I'm open to switching the default.

**Comment by roryabraham** [comment]
> IMHO, process.cwd() should be not treated as static in most cases

I think I agree. I am using `ncc` in the context of CI/CD (Github Actions), and I need to be able to compile scripts locally and run them on various remote machines. But if I include a dependency that uses `process.cwd`, then the scripts I compile locally won't work on the remote runners, because they'll include filepaths on my local machine.

**Comment by guybedford** [comment]
@roryabraham the safe route here is always to set the `cwd` option. A PR to improve the default would be welcome too.
